### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by androsland** [QoboLtd/project-template-wordpress#44]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/phpunit 4.6.6 -> satisfiable by phpunit/phpunit[4.6.6].
    - phpunit/phpunit 4.6.6 requires ext-dom * -> the requested PHP extension dom is missing from your system.

**Comment by androsland** [comment]
you just need to install php-xml extension

**Comment by mamchenkov** [comment]
Yup.  When composer complains about ext-*, it means you  need to install the appropriate PHP extension.  This because PHP extensions are usually system-wide and require root access and service restart, while composer mostly handles project-level dependencies and can work without elevated privileges.
